---
title: "Assignment 3"
author: "Zach Lehman"
date: "28/01/2021"
output: html_document
---

# Assignment 3

## Project Info
Author: Zach Lehman
Date: January 28, 2021
GitHub repository: https://github.com/zachheus/Assign-3
Username: @zachheus

### Visualizing Data

```{r}
library(dplyr) #load the dplyr package for future use
setwd("/Users/zachlehman/OneDrive - Queen's University/BIOL 432/Assign-3/InputData/") #setting my working directory to the location on my computer where the fallopia data csv file can be found
mydata<-read.csv("FallopiaData.csv") #reads the fallopia data csv file and puts it in a dataframe
```

```{r}
mydata1<-filter(mydata, Total>60) #filters out rows where the value for Total is less than 60
head(mydata1) #checking the first 6 rows of the new dataframe to ensure that my filter worked
```

```{r}
mydata2<-mydata1%>% #beginning to make a new dataframe using mydata1, and piping the following functions together so that I dont need to make several different objects
  select(Total, Taxon, Scenario, Nutrients)%>% #selecting the Total, Taxon, Scenario, and Nutrients columns to be the only ones seen, and in the order I decide
  mutate(TotalG=Total/1000)%>% #creating a new column called TotalG to get convert the units for Total from mg into g by dividing by 1000
  select(TotalG, Taxon, Scenario, Nutrients) #selecting the TotalG, Taxon, Scenario, and Nutrients colums to be the only ones seen, and in the order I decide
head(mydata2) #checking the first 6 rows of the new dataframe to ensure that my functions worked
```

```{r}
my.function<-function(var1=0,var2=0){ #creating the function and setting the default variable values as 0 for each, beginning a loop for the different parts of my equation
  if(var2=="Average"){ #if statement checking if variable 2 = Average
    print(summarise(var1, mean=mean(var1))) #if variable 2 = Average, it prints the mean of variable 1
  }
  else if(var2=="Sum"){ #if statement checking if variable 2 = Sum
    print(sum(var1)) #if variable 2 = Sum, it prints the sum of variable 1
  }
  else if(var2=="Observations"){ #if statement checking if variable 2 = Observations
    print(summary(var1)) #if variable 2 = Observations, it prints a summary of variable 1 which gives a count of how many items there are in the variable
  }
  else{ #if none of the above conditions are met,
    print("Error") #prints a string that just says Error
  } #finishes off the loop

outlist<-list(input1=var1, input2=var2) #creating the outlist
return(outlist) #returning the outlist so that the function now exists
}
```

```{r}
my.function(var1=mydata2$Taxon, var2="Observations") #using the function to count the number of taxa in mydata2, using the observations variable
```

```{r}
my.function(var1=mydata2$TotalG, var2="Average") #using the function to determine the mean values of TotalG between the nutrient levels, doing by using group_by to separate the data into the high or low Nutrients condition, then calculating the mean of each condition
```

```{r}
mydata3<-mydata2%>% #creating a new dataframe to use for this equation, piping to two different functions
  group_by(Nutrients)%>% #allows the data to be grouped by their nutrient level
  summarise(mean=mean(TotalG)) #produces a data.frame which is a table consisting of the nutrient level and their means

my.function(var1=mydata3, var2="Average") #prints the mean for each nutrient level
```

```{r}
write.csv(mydata2,"/Users/zachlehman/OneDrive - Queen's University/BIOL 432/Assign-3/Output/'WrangledData.csv") #creates a new csv file for mydata2 and puts it in the output folder
```
